dist: xenial

language: python

branches:
  except:
    - gh-pages

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"


install:
  - python setup.py install
  - pip install pytest pytest-cov pytest-pep8

script:
  - py.test -vvv --pep8 --cov=pcapng --cov-report=term-missing tests

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"
