dist: xenial

language: python

branches:
  except:
    - gh-pages

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"


install:
  - pip install .[dev]

script:
  - py.test -vvv --pycodestyle --cov=pcapng --cov-report=term-missing tests
