dist: xenial

language: python

branches:
  except:
    - gh-pages

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"


install:
  - python setup.py install
  - pip install pytest pytest-cov pytest-pep8

script:
  - py.test -vvv --pep8 --cov=pcapng --cov-report=term-missing tests
